# Generated by Django 5.1.3 on 2024-12-01 23:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jc_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_source', models.CharField(max_length=150)),
                ('job_target', models.CharField(max_length=150)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_links', to='plan_it_mvp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_name', models.CharField(max_length=150)),
                ('is_virtual', models.BooleanField(default=False)),
                ('pp_ac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=150)),
                ('out_ready', models.CharField(blank=True, max_length=150)),
                ('in_ready', models.CharField(blank=True, max_length=150)),
                ('job_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_duration', models.CharField(blank=True, max_length=150)),
                ('job_end', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('job_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_jobs', to='plan_it_mvp.job')),
                ('job_prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_jobs', to='plan_it_mvp.job')),
                ('job_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='plan_it_mvp.jobclass')),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='plan_it_mvp.project')),
                ('job_processing_unit', models.ManyToManyField(related_name='jobs', to='plan_it_mvp.projectparticipants')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_templates', to='plan_it_mvp.project')),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jt_class', models.CharField(max_length=150)),
                ('jt_name', models.CharField(max_length=150)),
                ('out_ready', models.CharField(max_length=150)),
                ('in_ready', models.CharField(max_length=150)),
                ('jt_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('jt_duration', models.CharField(blank=True, max_length=150)),
                ('jt_end', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('jt_processing_role', models.CharField(blank=True, max_length=150)),
                ('jt_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_jobs', to='plan_it_mvp.jobtemplate')),
                ('jt_prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_jobs', to='plan_it_mvp.jobtemplate')),
                ('project_templates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='plan_it_mvp.projecttemplate')),
                ('pt_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plan_it_mvp.projecttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='HardLinkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobt_source', models.CharField(max_length=150)),
                ('jobt_target', models.CharField(max_length=150)),
                ('project_templates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hard_links', to='plan_it_mvp.projecttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150)),
                ('project_participants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_roles', to='plan_it_mvp.projectparticipants')),
                ('project_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_roles', to='plan_it_mvp.projecttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='jobclass',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_class', to='plan_it_mvp.role'),
        ),
    ]
